### PR TITLE
EEPROM: - allow wpakey with up to 40 chars

### PR DESCRIPTION
**Pull request by Memphiz**
My wpa key is longer then 20 characters and I struggled for a while with culfw.esp8266 until I realized the limit in the code.

I doubled it with this PR.

This is an incompatible change in regard to the EEPROM format. I was not sure if I should set the Version to 68 now or how to handle this properly.

### CODE REVIEW

**Comment by Man-fred** [comment]
Hi Memphis,
you're right. I had copied EE_STR_LEN for ssid and key and this wasn't right. So this is a breaking update, the best is to change the length to the official maximum of ssid to 32 (31 + terminating \0) and key to 64.

VERSION shoud be left to 1.67, so this is the official last culfw-version. But VERSION_OTA must set to V01-67-01 for over-the-air updates.

I will test whether the AP starts after the update. Then this seems to be a good change.

**Comment by Memphiz** [comment]
Thx for the feedback - I will take care of it in the next couple of days I hope :)

**Comment by Memphiz** [comment]
I have updated the PR accordingly.

**Comment by lolorc** [comment]
I'm actually using it. looks ok. Thanks

**Pull request merged**
